次の2次元NumPy配列`data_2d`が与えられています。各列ごとに標準化を行ってください。標準化とは、各要素から平均値を引き、その結果を標準偏差で割る処理のことです。ただしscikit-learn、SciPyは用いないでください

In [25]:
import numpy as np

data_2d = np.array([[1, 10],
                    [2, 20],
                    [3, 30]])

### ここに各列ごとに標準化する処理を記述してください ###
standardized_data_2d = (data_2d - np.average(data_2d, axis=0))/np.std(data_2d, axis = 0)

print("元の2次元データ:\n", data_2d)
print("標準化された2次元データ（列ごと）:\n", standardized_data_2d)

元の2次元データ:
 [[ 1 10]
 [ 2 20]
 [ 3 30]]
標準化された2次元データ（列ごと）:
 [[-1.22474487 -1.22474487]
 [ 0.          0.        ]
 [ 1.22474487  1.22474487]]


In [ ]:
import numpy as np
data_2d = np.array([[1, 10],
                    [2, 20],
                    [3, 30]])
# print(data_2d)

# 各列の平均値を求める
data_2d_ave = np.average(data_2d, axis=0)
# print(data_2d_ave)

# 各列の標準偏差を求める
data_2d_std = np.std(data_2d, axis = 0)
# print(data_2d_std)

# 各列を標準
data_2d_norm = (data_2d - data_2d_ave)/data_2d_std# ここブロードキャスト！

print(data_2d_norm)

[ 2. 20.]
[0.81649658 8.16496581]
[[-1.22474487 -1.22474487]
 [ 0.          0.        ]
 [ 1.22474487  1.22474487]]
